# Generated by Django 4.2.7 on 2024-03-23 02:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_cover_image_alter_project_cover_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='sq-front/src/assets'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='sq-front/src/assets'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_video',
            field=models.FileField(blank=True, upload_to='sq-front/src/assets'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
