# Generated by Django 4.2.7 on 2024-03-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_galleryimage_image_alter_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='./'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_video',
            field=models.FileField(blank=True, upload_to='./'),
        ),
    ]
