# Generated by Django 4.2.7 on 2023-12-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('student', models.CharField(max_length=30)),
                ('lessons', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
