# Generated by Django 4.2.7 on 2023-12-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='built_with',
            field=models.BooleanField(default=False),
        ),
    ]
