# Generated by Django 4.2.7 on 2023-12-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_subskill_built_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subskill',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
