# Generated by Django 4.2.7 on 2024-05-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitem',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
