# Generated by Django 4.2.7 on 2024-05-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resumeitem_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeitem',
            options={'ordering': ['-end_date']},
        ),
    ]
