name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  django-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install

      - name: Create frontend .env
        run: |
          cd sq-front
          echo "${{ secrets.FRONTEND_ENV_CONTENTS }}" > .env
          cd ../

      - name: Create .env
        run: |
          echo "ALLOWED_ORIGINS=$ALLOWED_ORIGINS" > .env
          echo "DEBUG_STATUS=$DEBUG_STATUS" > .env
          echo "SECRET_KEY=$SECRET_KEY" > .env
          echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > .env
          echo "WEBHOOK_KEY=$WEBHOOK_KEY" > .env
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          DEBUG_STATUS: ${{ secrets.DEBUG_STATUS }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}

      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary

      - name: Accept host fingerprint
        run: |
          ssh -o StrictHostKeyChecking=accept-new root@strange-quark.com "ls"

      - name: Run up
        run: |
          pipenv run python manage.py up strange-quark.com --email=kae.unterseher@gmail.com
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

      - name: Remove .env
        run: rm .env
